name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: keycase
      - uses: actions/checkout@v4
        with:
          repository: keycase/core
          path: core
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
        working-directory: keycase
      - run: dart analyze --fatal-infos
        working-directory: keycase
